image: python:3.7

stages:
  - test
  - build

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python3 -V  # Print out python version for debugging
  - pip install virtualenv -i https://pypi.douban.com/simple
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt -i https://pypi.douban.com/simple

test:
  stage: test
  script:
    - pip install pytest pyyaml coverage -i https://pypi.douban.com/simple
    - coverage run -m pytest
    - coverage report
    - coverage html -d coverage.report
  artifacts:
    paths:
      - coverage.report/*
  only:
    - master
    - develop
    - /^feat.*$/

build:
  stage: build
  script:
    - python setup.py sdist
    - pip install twine -i https://pypi.douban.com/simple
    - twine upload --repository-url http://pypi.aengine.com.cn/ -u $AENGINE_PYPI_ACCOUNT -p $AENGINE_PYPI_PASSWORD dist/*
  artifacts:
    paths:
      - dist/*
      - coverage.report/*
  only:
    - master
